# typed: false
# frozen_string_literal: true

# veric — attribute-grammar-powered metadata governance for dbt
#
# This file is the source-of-truth template for the
# `veric-dev/homebrew-veric` tap. It is bumped automatically by
# `.github/workflows/bump-homebrew-formula.yml` on each public
# release: the `version`, `sha256`, and `url` lines below are
# rewritten in place from the release's `.sha256` companion files.
#
# The formula intentionally mirrors what `dbt-labs/homebrew-dbt`
# does — single binary, two architectures, no Python, no rebuild on
# install. macOS arm64 + Linux x86_64 are the v0.1 target matrix
# (matches `cli-release.yml`).
#
# To install from this template manually:
#   brew install ./templates/homebrew/Formula/veric.rb
# but downstream users go through the tap:
#   brew tap veric-dev/veric
#   brew install veric

class Veric < Formula
  desc "Attribute-grammar-powered metadata governance for dbt"
  homepage "https://veric.dev"
  version "0.1.0"
  license "LicenseRef-Veric-Commercial"

  on_macos do
    on_arm do
      url "https://github.com/veric-dev/veric/releases/download/v#{version}/veric-#{version}-macos-arm64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end

    on_intel do
      odie "veric does not yet ship an Intel macOS binary. Build from source or wait for a future release."
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/veric-dev/veric/releases/download/v#{version}/veric-#{version}-linux-x86_64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end

    on_arm do
      odie "veric does not yet ship an arm64 Linux binary. Build from source or wait for a future release."
    end
  end

  def install
    bin.install "veric"
    # THIRD-PARTY-NOTICES is generated by cargo-about during the
    # release workflow and shipped inside the tarball; if it's
    # absent (e.g. a hand-built binary) skip the doc step rather
    # than fail the install.
    doc.install "THIRD-PARTY-NOTICES" if File.exist?("THIRD-PARTY-NOTICES")
    doc.install "README.md" if File.exist?("README.md")
  end

  def caveats
    <<~EOS
      veric ships as a single binary. For first-run guidance:

        veric init           # bootstrap workspace.yml + .veric/policy.toml
        veric scan           # ingest + analyze + push to the SaaS

      Telemetry is OFF by default in v0.1. To keep it off when v0.2
      ships an opt-out announcement, set:
        export VERIC_NO_TELEMETRY=1

      Privacy: https://veric.dev/privacy
    EOS
  end

  test do
    # Smoke check: --version exits 0 and contains the version string.
    assert_match version.to_s, shell_output("#{bin}/veric --version")
    # Smoke check: roadmap-gated commands print the expected banner
    # on stderr and exit non-zero (78) per spec.
    output = shell_output("#{bin}/veric capabilities 2>&1", 0)
    refute_empty output
  end
end
